

disabled_rules:
  - identifier_name
  - force_cast
  - force_try
  - trailing_whitespace
  - type_name
  
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - cyclomatic_complexity
  - empty_count
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - file_header
  - first_where
  - missing_docs
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
  - valid_docs

private_outlet:
  allow_private_set: true