

disabled_rules:
  - cyclomatic_complexity
  - empty_count
  - file_header
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - missing_docs
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
  
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - first_where
  - nimble_operator
  - number_separator
  - object_literal
  - operator_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline

private_outlet:
  allow_private_set: true